<template>
  <div class="space-y-6 pb-10">
    <!-- Header Hero Banner -->
    <section class="rounded-xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-6 sm:gap-10">
      <div>
        <p class="text-[9px] uppercase tracking-wider text-indigo-600 font-extrabold">Academic Summary</p>
        <h1 class="mt-1 text-2xl font-extrabold text-slate-900 tracking-tight leading-tight font-sans">
          Performance Dashboard
        </h1>
        <p class="mt-2.5 max-w-xl text-xs leading-relaxed text-slate-500 font-semibold">
          Monitor semester grade averages, completed course credits, and review intelligent suggestions generated by GPA trends.
        </p>
      </div>
      <div 
        :data-context-student-id="selectedStudent?.id || null"
        class="rounded-lg bg-slate-50 border border-slate-200 p-5 text-slate-800 w-full sm:w-64 mt-6 sm:mt-0 sm:ml-6 shadow-sm shrink-0"
      >
        <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">Session Profile</p>
        <p class="mt-1.5 text-sm font-bold text-slate-900 tracking-tight">{{ sessionProfileName }}</p>
        <p class="mt-1 text-[10px] text-slate-500 font-medium leading-relaxed">Click navigation links to edit course marks or check lists.</p>
      </div>
    </section>

    <!-- Error Alert -->
    <div v-if="error" class="rounded-lg bg-rose-50 border border-rose-100 p-4 text-xs font-semibold text-rose-600 leading-normal">
      {{ error }}
    </div>

    <!-- Loading Overlay -->
    <div v-if="loading" class="flex flex-col items-center justify-center py-20 gap-2.5">
      <svg class="animate-spin h-6 w-6 text-slate-800" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
      </svg>
      <span class="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Refreshing analytics...</span>
    </div>

    <template v-else>
      <!-- Metric Cards Grid -->
      <section class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <DashboardCard title="Current GPA" :value="currentGpa.toFixed(2)" detail="Across completed modules" accent="indigo" />
        <DashboardCard title="Current CGPA" :value="currentCgpa.toFixed(2)" detail="Cumulative score projection" accent="cyan" />
        <DashboardCard title="Total Courses" :value="totalCourses" detail="Active modules registered" accent="slate" />
        <DashboardCard title="Failed Courses" :value="failedCourses" detail="Requires retake/re-audit" accent="rose" />
      </section>

      <!-- Charts Layout -->
      <section class="grid gap-6 lg:grid-cols-[1.4fr_0.9fr]">
        <div class="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm flex flex-col justify-between">
          <div>
            <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">progression mapping</p>
            <h2 class="mt-1 text-sm font-bold text-slate-900 tracking-tight">GPA Progression Trend</h2>
          </div>
          <div class="mt-4">
            <charts-GpaTrendChart :data="gpaTrendData" />
          </div>
        </div>

        <div class="grid gap-6">
          <div class="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm">
            <div>
              <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">Breakdown by Semester</p>
              <h2 class="mt-1 text-sm font-bold text-slate-900 tracking-tight">Semester Marks %</h2>
            </div>
            <div class="mt-4">
              <charts-SemesterPerformanceChart :data="semesterPerformanceData" />
            </div>
          </div>

          <div class="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm">
            <div>
              <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">Summary Metrics</p>
              <h2 class="mt-1 text-sm font-bold text-slate-900 tracking-tight">Overall Grade Distribution</h2>
            </div>
            <div class="mt-4 flex flex-col sm:flex-row items-center gap-4 justify-around">
              <charts-GradeDistributionChart :data="gradeDistributionData" />
              <div class="grid gap-1.5 text-xs font-semibold text-slate-600 w-full max-w-[150px]">
                <div v-for="entry in gradeDistributionData.slice(0, 4)" :key="entry.grade" class="flex items-center justify-between rounded border border-slate-100 bg-slate-50/50 px-2.5 py-1.5 text-[10px]">
                  <span class="text-slate-900 font-bold">Grade {{ entry.grade }}</span>
                  <span class="text-slate-400 font-bold">{{ entry.count }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Tables and Action Items Grid -->
      <section class="grid gap-6 lg:grid-cols-[1.5fr_1fr]">
        <!-- Course Progress Load -->
        <div class="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm space-y-4">
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">Transcript Load</p>
              <h2 class="mt-1 text-sm font-bold text-slate-900 tracking-tight">Current Course Statuses</h2>
            </div>
            <div class="inline-flex rounded border border-slate-200 bg-slate-50 px-2 py-0.5 text-[9px] font-bold text-slate-500 uppercase tracking-wider">
              Static Data Cache
            </div>
          </div>
          <CourseTable :rows="courseRows" />
        </div>

        <!-- Recommendations Block -->
        <div class="rounded-xl border border-slate-200/80 bg-white p-5 shadow-sm space-y-4">
          <div>
            <p class="text-[9px] uppercase tracking-wider text-slate-400 font-bold">System Advice</p>
            <h2 class="text-sm font-bold text-slate-900 tracking-tight">Study Action suggestions</h2>
          </div>
          <div class="space-y-2.5">
            <RecommendationCard 
              v-for="item in recommendations" 
              :key="item.title" 
              :title="item.title" 
              :description="item.description" 
            />
          </div>
        </div>
      </section>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import type { Student, AnalysisResult } from '~/types'
import { useApi } from '~/composables/useApi'
import { useAuth } from '~/composables/useAuth'

const api = useApi()
const { user } = useAuth()

const selectedStudent = ref<Student | null>(null)
const analysis = ref<AnalysisResult | null>(null)
const loading = ref(true)
const error = ref<string | null>(null)

const loadData = async () => {
  try {
    loading.value = true
    error.value = null
    const studentsList = await api<Student[]>('/students')
    if (studentsList && studentsList.length) {
      const matched = studentsList.find(s => s.email === user.value?.email)
      if (matched) {
        selectedStudent.value = matched
      } else {
        selectedStudent.value = studentsList[0] ?? null
      }
      
      if (selectedStudent.value) {
        const result = await api<AnalysisResult>(`/students/${selectedStudent.value.id}/analysis`)
        analysis.value = result
      }
    }
  } catch (err) {
    console.error('Failed to load dashboard metrics:', err)
    error.value = 'Unable to connect to the backend server. Using offline fallback metrics.'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})

const courseRows = computed(() => {
  return analysis.value?.courses || [
    { code: 'CSC101', title: 'Programming Fundamentals', semester: 'Fall 2025', credits: 3, grade: 'A-', status: 'Passed' },
    { code: 'MTH112', title: 'Calculus II', semester: 'Fall 2025', credits: 4, grade: 'B+', status: 'Passed' },
    { code: 'PHY110', title: 'Physics for Engineers', semester: 'Fall 2025', credits: 3, grade: 'C', status: 'Passed' },
    { code: 'ENG105', title: 'Academic Writing', semester: 'Fall 2025', credits: 2, grade: 'B', status: 'Passed' },
    { code: 'HIS120', title: 'Modern History', semester: 'Spring 2026', credits: 2, grade: 'D+', status: 'Failed' },
  ]
})

const sessionProfileName = computed(() => {
  if (selectedStudent.value?.email === user.value?.email) {
    return selectedStudent.value?.name
  }
  if (user.value) {
    return user.value.username
      .split('.')
      .map((s: string) => s.charAt(0).toUpperCase() + s.slice(1))
      .join(' ')
  }
  return selectedStudent.value?.name || 'Student User'
})

const currentGpa = computed(() => analysis.value?.gpa ?? 3.38)
const currentCgpa = computed(() => analysis.value?.cgpa ?? 3.45)
const totalCourses = computed(() => analysis.value?.courseCount ?? courseRows.value.length)
const failedCourses = computed(() => {
  return analysis.value?.failedCourses ?? courseRows.value.filter(c => c.status.toLowerCase() === 'failed').length
})

const recommendations = computed(() => {
  return analysis.value?.recommendations || [
    { title: 'Improve time management', description: 'Start each week with a study schedule and dedicate focused blocks for critical topics.' },
    { title: 'Review weak subjects', description: 'Revisit the materials for courses below B and complete a short weekly practice review.' }
  ]
})

const gpaTrendData = [
  { term: 'Fall 2024', gpa: 3.15 },
  { term: 'Spring 2025', gpa: 3.38 },
  { term: 'Fall 2025', gpa: 3.52 },
  { term: 'Spring 2026', gpa: 3.45 },
  { term: 'Summer 2026', gpa: 3.62 },
]

const semesterPerformanceData = [
  { semester: 'Fall 2024', performance: 78 },
  { semester: 'Spring 2025', performance: 82 },
  { semester: 'Fall 2025', performance: 88 },
  { semester: 'Spring 2026', performance: 84 },
]

const gradeDistributionData = [
  { grade: 'A', count: 12 },
  { grade: 'B', count: 9 },
  { grade: 'C', count: 5 },
  { grade: 'D', count: 2 },
  { grade: 'F', count: 1 },
]
</script>
